// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qncqjadnipqjowsntgzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuY3FqYWRuaXBxam93c250Z3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNjg1NDksImV4cCI6MjA2OTc0NDU0OX0._lFWqhptGiPh3w6WUnr_Ag4pN8XyWsflz2pyiKlHlGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});